# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: mikekonan
    name: exchange-proxy
  draft: true
  name_template: "{{.ProjectName}}-v{{.Version}}"

dockers:
  - image_templates:
      - mikekonan/exchange-proxy:latest-amd64
      - mikekonan/exchange-proxy:{{ .Version }}-amd64
    dockerfile: docker/ci.Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--build-arg=VERSION={{ .Version }}"
      - "--platform=linux/amd64"

  - image_templates:
      - mikekonan/exchange-proxy:latest-arm64
      - mikekonan/exchange-proxy:{{ .Version }}-arm64
    dockerfile: docker/ci.Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--build-arg=VERSION={{ .Version }}"
      - "--platform=linux/arm64"

  - image_templates:
      - mikekonan/exchange-proxy:latest-arm-v7
      - mikekonan/exchange-proxy:{{ .Version }}-arm-v7
    dockerfile: docker/ci.Dockerfile
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--build-arg=VERSION={{ .Version }}"
      - "--platform=linux/arm/v7"

  - image_templates:
      - mikekonan/exchange-proxy:latest-arm-v6
      - mikekonan/exchange-proxy:{{ .Version }}-arm-v6
    dockerfile: docker/ci.Dockerfile
    use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    build_flag_templates:
      - "--build-arg=VERSION={{ .Version }}"
      - "--platform=linux/arm/v6"
